name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --force --ignore-scripts

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Configure EAS Project
        run: |
          cat << 'EOF' > eas.json
          {
            "cli": {
              "appVersionSource": "remote"
            },
            "build": {
              "preview": {
                "android": {
                  "buildType": "apk"
                }
              }
            }
          }
          EOF

      - name: Link EAS Project
        run: eas init --id 5c29accf-1f88-4c3b-953e-fdaad87b4d7d --force --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build APK with EAS
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
